[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
sss_1 = "47TNsKC1iJvLTKYRMbfYjrod4a56YE1f4qv73hZkdWUZ"
sss_2 = "8DMsf39fGWfcrWVjfyEq8fqZf5YcTvVPGgdJr8s2S8Nc"

[programs.localnet]
sss_1 = "47TNsKC1iJvLTKYRMbfYjrod4a56YE1f4qv73hZkdWUZ"
sss_2 = "8DMsf39fGWfcrWVjfyEq8fqZf5YcTvVPGgdJr8s2S8Nc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/sss1-lifecycle.test.ts tests/sss2-compliance.test.ts tests/roles-and-minters.test.ts tests/edge-cases.test.ts tests/authority-transfer.test.ts tests/sss-sdk.test.ts"
