[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
sss_token = "BMWu6XvhKMXitwv3FCjjm2zZGD4pXeB1KX5oiUcPxGDB"
sss_transfer_hook = "GtYvo8PY7hV3KWfGHs3fPDyFEHRV4t1PVw6BkYUBgctC"

[programs.localnet]
sss_token = "BMWu6XvhKMXitwv3FCjjm2zZGD4pXeB1KX5oiUcPxGDB"
sss_transfer_hook = "GtYvo8PY7hV3KWfGHs3fPDyFEHRV4t1PVw6BkYUBgctC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/sss-token.test.ts tests/sss-transfer-hook.test.ts"
